improvado:
  outputs:
    dev:
      <optional_config>: <value>
      dataset: austin_incidents
      keyfile: "{{ env_var('DBT_PROFILES_DIR') }}/improvado.json"
      method: service-account
      project: dbtshopify
      threads: 1
      type: bigquery
  target: dev
