improvado:
  outputs:
    dev:
      <optional_config>: <value>
      dataset: austin_incidents
      keyfile: "improvado_shopify_internee/dbt_shopify/improvado/improvado.json"
      method: service-account
      project: dbtshopify
      threads: 1
      type: bigquery
  target: dev
