name: dbt deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dbt
        run: pip install dbt-bigquery
      - name: Print DBT_PROFILES_DIR
        run: echo $DBT_PROFILES_DIR
      - name: Install Dependencies
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/dbt_shopify/improvado/
          dbt deps --profiles-dir ${{ github.workspace }} --profile improvado
      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}
          BIGQUERY_KEY: ${{ secrets.BIGQUERY_KEY }}
        run: |
          cd ${{ github.workspace }}/dbt_shopify/improvado/
          dbt run --profiles-dir ${{ github.workspace }} --profile improvado
      - name: Run dbt tests
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}
          BIGQUERY_KEY: ${{ secrets.BIGQUERY_KEY }}
        run: |
          cd ${{ github.workspace }}/dbt_shopify/improvado/
          dbt test --profiles-dir ${{ github.workspace }} --profile improvado

