name: dbt deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dbt
        run: pip install dbt-bigquery
      - name: Install dbt dependencies
        run: dbt deps --profiles-dir dbt_shopify/improvado/
      - name: Print DBT_PROFILES_DIR
        run: echo $DBT_PROFILES_DIR
      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt_shopify/improvado/
        run: |
          cd ${{ github.workspace }}/dbt_shopify/improvado/
          dbt run --profiles-dir . --profile improvado



