name: dbt deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dbt
        run: pip install dbt-bigquery
      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}
        run: dbt run --profiles-dir ../ --profile ${{ secrets.DBT_PROFILE }}
